projects:
  testamplify:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 3ojwjm732rdija4hdlzbsmoa3m
      endpoints:
        prod: >-
          https://3udtow5vnjarzg4ugacnbt52ae.appsync-api.us-east-1.amazonaws.com/graphql
